[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
clap = { version = "4.5.20", features = ["derive"] }
ndarray = "0.16.1"
ndarray-linalg = {version = "0.16.0", featues = ["solve"]}
regex = "1.11.1"
